# Pandas - Introduction
---
## Introduction:

In this notebook, I'll explore Pandas, a powerful Python library for data manipulation and analysis. I'll cover essential topics that helped me get started with Pandas and perform common data tasks efficiently.

I'll use a dataset provided by `IBM`, which contains information about top-selling albums.

### Table of Contents:

<li> <a href="#data-structures">Data Structures</a> </li>
<li> <a href="#read-write">Reading and Writing Data with Pandas</a> </li>
<li> <a href="#indexing">Indexing and Selection</a> </li>
<li> <a href="#exploration">Data Exploration</a> </li>
<li> <a href="#cleaning">Data Cleaning and Preprocessing</a> </li>

In [2]:
# Import library
import pandas as pd

<h2 id="data-structures">1. Data Structures</h2>

- ```Series```:  One-dimensional labeled array capable of holding any data type (integers, strings, floats, etc.).
- ```DataFrame```: Two-dimensional labeled data structure with columns of potentially different types.

Pandas provides both index and data labels, making it a powerful tool for data manipulation and analysis.

The rows are called **index**.

### Series:

In [2]:
# Padas Series
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
df_planets = pd.Series(data=planets)
df_planets

0    Mercury
1      Venus
2      Earth
3       Mars
4    Jupiter
5     Saturn
6     Uranus
7    Neptune
dtype: object

In [3]:
# Set index values
planets = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
position = [1, 2, 3, 4, 5, 6, 7, 8]
df_planets = pd.Series(data=position, index=planets)
df_planets

Mercury    1
Venus      2
Earth      3
Mars       4
Jupiter    5
Saturn     6
Uranus     7
Neptune    8
dtype: int64

In [4]:
# Dictionary to Series
solar_system_planets = {"Mercury": 1, 
                        "Venus": 2, 
                        "Earth": 3, 
                        "Mars": 4,
                        "Jupiter": 5, 
                        "Saturn": 6, 
                        "Uranus": 7, 
                        "Neptune": 8      
                        }

df_planets = pd.Series(data=solar_system_planets)
df_planets

Mercury    1
Venus      2
Earth      3
Mars       4
Jupiter    5
Saturn     6
Uranus     7
Neptune    8
dtype: int64

### DataFrames:

In [5]:
# Create a DataFrame
data = {'Planet': ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"],
        'Position': [1, 2, 3, 4, 5, 6, 7, 8],
        'Radius': [2439, 6052, 6371, 3389, 69911, 58232, 25362, 24622]
        }

df_planets = pd.DataFrame(data)
df_planets

    Planet  Position  Radius
0  Mercury         1    2439
1    Venus         2    6052
2    Earth         3    6371
3     Mars         4    3389
4  Jupiter         5   69911
5   Saturn         6   58232
6   Uranus         7   25362
7  Neptune         8   24622

In [6]:
# Create a DataFrame from list or Series
planet = ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"]
position = [1, 2, 3, 4, 5, 6, 7, 8]
radius = [2439, 6052, 6371, 3389, 69911, 58232, 25362, 24622]

df_planets = pd.DataFrame(data=[planet, position, radius], index=['Planet', 'Position', 'Radius'])
df_planets

                0      1      2     3        4       5       6        7
Planet    Mercury  Venus  Earth  Mars  Jupiter  Saturn  Uranus  Neptune
Position        1      2      3     4        5       6       7        8
Radius       2439   6052   6371  3389    69911   58232   25362    24622

In [7]:
# Transpose 
df_planets.T     # df_planets.transpose()

    Planet Position Radius
0  Mercury        1   2439
1    Venus        2   6052
2    Earth        3   6371
3     Mars        4   3389
4  Jupiter        5  69911
5   Saturn        6  58232
6   Uranus        7  25362
7  Neptune        8  24622

In [8]:
data = {'Planet': ["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune"],
        'Position': [1, 2, 3, 4, 5, 6, 7, 8],
        'Radius': [2439, 6052, 6371, 3389, 69911, 58232, 25362, 24622]
        }

df_planets = pd.DataFrame(data)

# Set a column as index
df_planets.set_index('Planet', inplace=True)
df_planets

         Position  Radius
Planet
Mercury         1    2439
Venus           2    6052
Earth           3    6371
Mars            4    3389
Jupiter         5   69911
Saturn          6   58232
Uranus          7   25362
Neptune         8   24622

In [9]:
# Reset index
df_planets.reset_index(inplace=True)
df_planets

    Planet  Position  Radius
0  Mercury         1    2439
1    Venus         2    6052
2    Earth         3    6371
3     Mars         4    3389
4  Jupiter         5   69911
5   Saturn         6   58232
6   Uranus         7   25362
7  Neptune         8   24622

In [10]:
# Get the columns
df_planets.columns

Index(['Planet', 'Position', 'Radius'], dtype='object')

In [11]:
# Get the inidices
df_planets.index.values

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [12]:
# Convert this into a list
print(df_planets.columns.tolist())
print(df_planets.index.tolist())

['Planet', 'Position', 'Radius']
[0, 1, 2, 3, 4, 5, 6, 7]

<h2 id="read-write">2. Reading and Writing Data with Pandas</h2>

Pandas provides functions to read data from various file formats such as CSV, Excel, SQL databases, JSON, and more:

```.csv```, ```.xlsx```, ```.zip```, ```.html```, ```.txt```, ```.json```.

In [3]:
# Read data from CSV file
csv_path = 'https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%204/Datasets/TopSellingAlbums.csv'
df = pd.read_csv(csv_path)

In [4]:
# Get the one column as a Series
x = df['Length']
print(type(x))
x

<class 'pandas.core.series.Series'>

0    0:42:19
1    0:42:11
2    0:42:49
3    0:57:44
4    0:46:33
5    0:43:08
6    1:15:54
7    0:40:01
Name: Length, dtype: object

In [5]:
# Get multiple columns
y = df[['Artist','Length','Genre']]
print(type(y))
y

<class 'pandas.core.frame.DataFrame'>

            Artist   Length                        Genre
0  Michael Jackson  0:42:19               pop, rock, R&B
1            AC/DC  0:42:11                    hard rock
2       Pink Floyd  0:42:49             progressive rock
3  Whitney Houston  0:57:44               R&B, soul, pop
4        Meat Loaf  0:46:33  hard rock, progressive rock
5           Eagles  0:43:08   rock, soft rock, folk rock
6         Bee Gees  1:15:54                        disco
7    Fleetwood Mac  0:40:01                    soft rock

<h2 id="exploration">3. Data Exploration</h2>

It's essential to explore and inspect the dataset. This section covers methods for viewing DataFrame contents, summarizing data statistics (e.g., mean, median, min, max), and accessing specific rows, columns, or cells within the DataFrame.

The ```.head()``` and ```.tail()``` will display either the first or the last five rows.

It is important to note ```.value_counts()``` function, which in Pandas is used to count the unique values in a Series or DataFrame column and return the counts as a new Series. This function is particularly useful for understanding the distribution of values within a categorical variable.

In [6]:
# Check the dimension of the dataframe (rows, columns)
df.shape

(8, 10)

In [7]:
# Display the first few rows of the DataFrame
df.head()

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0

In [8]:
# Check data types of columns
df.dtypes

Artist                               object
Album                                object
Released                              int64
Length                               object
Genre                                object
Music Recording Sales (millions)    float64
Claimed Sales (millions)              int64
Released.1                           object
Soundtrack                           object
Rating                              float64
dtype: object

In [9]:
# Display basic information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Artist                            8 non-null      object
 1   Album                             8 non-null      object
 2   Released                          8 non-null      int64
 3   Length                            8 non-null      object
 4   Genre                             8 non-null      object
 5   Music Recording Sales (millions)  8 non-null      float64
 6   Claimed Sales (millions)          8 non-null      int64
 7   Released.1                        8 non-null      object
 8   Soundtrack                        2 non-null      object
 9   Rating                            8 non-null      float64
dtypes: float64(2), int64(2), object(6)
memory usage: 768.0+ bytes

In [10]:
# Display summary statistics of numerical columns
df.describe()

,Released,Music Recording Sales (millions),Claimed Sales (millions),Rating
count,8.000000,8.000000,8.000000,8.000000
mean,1979.250000,28.125000,46.125000,8.250000
std,5.800246,8.189322,8.271077,1.224745
min,1973.000000,20.600000,40.000000,6.500000
25%,1976.750000,23.300000,41.500000,7.375000
50%,1977.000000,26.750000,43.500000,8.250000
75%,1980.500000,28.975000,46.250000,9.125000
max,1992.000000,46.000000,65.000000,10.000000

In [12]:
# Display summary statistics of categorical columns
df.select_dtypes(exclude=['number']).describe()

,Artist,Album,Length,Genre,Released.1,Soundtrack
count,8,8,8,8,8,2
unique,8,8,8,8,8,1
top,Michael Jackson,Thriller,0:42:19,"pop, rock, R&B",30-Nov-82,Y
freq,1,1,1,1,1,2

In [11]:
# Display summary statistics of numerical and categorical columns
df.describe(include='all')

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
count,8,8,8.000000,8,8,8.000000,8.000000,8,2,8.000000
unique,8,8,NaN,8,8,NaN,NaN,8,1,NaN
top,Michael Jackson,Thriller,NaN,0:42:19,"pop, rock, R&B",NaN,NaN,30-Nov-82,Y,NaN
freq,1,1,NaN,1,1,NaN,NaN,1,2,NaN
mean,NaN,NaN,1979.250000,NaN,NaN,28.125000,46.125000,NaN,NaN,8.250000
std,NaN,NaN,5.800246,NaN,NaN,8.189322,8.271077,NaN,NaN,1.224745
min,NaN,NaN,1973.000000,NaN,NaN,20.600000,40.000000,NaN,NaN,6.500000
25%,NaN,NaN,1976.750000,NaN,NaN,23.300000,41.500000,NaN,NaN,7.375000
50%,NaN,NaN,1977.000000,NaN,NaN,26.750000,43.500000,NaN,NaN,8.250000
75%,NaN,NaN,1980.500000,NaN,NaN,28.975000,46.250000,NaN,NaN,9.125000
max,NaN,NaN,1992.000000,NaN,NaN,46.000000,65.000000,NaN,NaN,10.000000

In [21]:
# Check for missing values in the DataFrame
df.isnull().sum()

Artist                              0
Album                               0
Released                            0
Length                              0
Genre                               0
Music Recording Sales (millions)    0
Claimed Sales (millions)            0
Released.1                          0
Soundtrack                          6
Rating                              0
dtype: int64

In [22]:
# Check for duplicate rows in the DataFrame
df.duplicated().sum()

0

In [23]:
# Display unique values in a specific column
df['Artist'].unique()

array(['Michael Jackson', 'AC/DC', 'Pink Floyd', 'Whitney Houston',
       'Meat Loaf', 'Eagles', 'Bee Gees', 'Fleetwood Mac'], dtype=object)

In [24]:
# Value counts in a specific column
df['Genre'].value_counts()

Genre
pop, rock, R&B                 1
hard rock                      1
progressive rock               1
R&B, soul, pop                 1
hard rock, progressive rock    1
rock, soft rock, folk rock     1
disco                          1
soft rock                      1
Name: count, dtype: int64

<h2 id="indexing">4. Indexing and Selection</h2>

One way to access unique elements is the <code>iloc</code> method, where you can access the 1st row and the 1st column as follows:

This section covers various methods for selecting rows, columns, or individual cells using label-based indexing (loc), positional indexing (iloc), and mixed indexing (ix)

```python
    df.loc[label]        
        #filters by the labels of the index/column
    df.iloc[index]       
        #filters by the positions of the index/column
```

#### .iloc[ ]:

In [25]:
# First Row and First Column
df.iloc[0, 0]

'Michael Jackson'

In [26]:
# All the Rows and specific Column
df.iloc[:, 2]

0    1982
1    1980
2    1973
3    1992
4    1977
5    1976
6    1977
7    1977
Name: Released, dtype: int64

In [27]:
# Multiple Rows and Columns
df.iloc[0:4, 1:4]

                       Album  Released   Length
0                   Thriller      1982  0:42:19
1              Back in Black      1980  0:42:11
2  The Dark Side of the Moon      1973  0:42:49
3              The Bodyguard      1992  0:57:44

In [28]:
# Select specific rows and columns
df.iloc[[1, 3], [0, 2]]

            Artist  Released
1            AC/DC      1980
3  Whitney Houston      1992

In [29]:
# Select all rows and specific columns
df.iloc[:, :2]

            Artist                            Album
0  Michael Jackson                         Thriller
1            AC/DC                    Back in Black
2       Pink Floyd        The Dark Side of the Moon
3  Whitney Houston                    The Bodyguard
4        Meat Loaf                  Bat Out of Hell
5           Eagles  Their Greatest Hits (1971-1975)
6         Bee Gees             Saturday Night Fever
7    Fleetwood Mac                          Rumours

In [30]:
# Select all rows and specific columns
df.iloc[:, [1, 3]]

                             Album   Length
0                         Thriller  0:42:19
1                    Back in Black  0:42:11
2        The Dark Side of the Moon  0:42:49
3                    The Bodyguard  0:57:44
4                  Bat Out of Hell  0:46:33
5  Their Greatest Hits (1971-1975)  0:43:08
6             Saturday Night Fever  1:15:54
7                          Rumours  0:40:01

#### .loc[ ]

It is used to select either index rows or column based on theri name.

In [31]:
# Select single row and single column
df.loc[1, 'Soundtrack']

nan

In [32]:
# Select multiple rows and columns
df.loc[1:3, 'Artist':'Length']

            Artist                      Album  Released   Length
1            AC/DC              Back in Black      1980  0:42:11
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49
3  Whitney Houston              The Bodyguard      1992  0:57:44

In [33]:
# Select specific rows and columns
df.loc[[1, 3], ['Soundtrack', 'Rating']]

  Soundtrack  Rating
1        NaN     9.5
3          Y     8.5

In [34]:
# Select all rows and specific columns
df.loc[:, ['Soundtrack', 'Rating']]

  Soundtrack  Rating
0        NaN    10.0
1        NaN     9.5
2        NaN     9.0
3          Y     8.5
4        NaN     8.0
5        NaN     7.5
6          Y     7.0
7        NaN     6.5

In [35]:
# Select all rows and specific columns
df[['Soundtrack', 'Rating']]

  Soundtrack  Rating
0        NaN    10.0
1        NaN     9.5
2        NaN     9.0
3          Y     8.5
4        NaN     8.0
5        NaN     7.5
6          Y     7.0
7        NaN     6.5

#### Conditional Selection

| Function           | Description                        |
|--------------------|------------------------------------|
| DataFrame.eq()    | Element-wise equality              |
| DataFrame.ne()    | Element-wise inequality            |
| DataFrame.lt()    | Element-wise less than             |
| DataFrame.le()    | Element-wise less than or equal to |
| DataFrame.gt()    | Element-wise greater than          |
| DataFrame.ge()    | Element-wise greater than or equal to |
| DataFrame.all()   | True if all elements are True      |
| DataFrame.any()   | True if any element is True        |
| DataFrame.notnull()| True for non-null elements        |
| DataFrame.isnull()| True for null elements             |
| DataFrame.isin()  | Element-wise membership test      |

In [36]:
# Create Pandas Series
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([5, 4, 3, 2, 1])

# Element-wise comparison
print("Element-wise comparison (greater than):")
print(s1 > s2)

# Element-wise logical AND
print("\nElement-wise logical AND:")
print((s1 > 2) & (s2 < 4))

# Element-wise membership test
print("\nElement-wise membership test:")
print(s1.isin([1, 3, 5]))

# Element-wise is null
s3 = pd.Series([1, None, 3, None, 5])
print("\nElement-wise is null:")
print(s3.isnull())

Element-wise comparison (greater than):
0    False
1    False
2    False
3     True
4     True
dtype: bool

Element-wise logical AND:
0    False
1    False
2     True
3     True
4     True
dtype: bool

Element-wise membership test:
0     True
1    False
2     True
3    False
4     True
dtype: bool

Element-wise is null:
0    False
1     True
2    False
3     True
4    False
dtype: bool

In [37]:
# Create a Pandas DataFrame
df_1 = pd.DataFrame({'A': [1, 2, 3, 4, 5],
                   'B': [5, 4, 3, 2, 1]})

# Element-wise equality
print("Element-wise equality:")
print(df_1.eq(3))

# Element-wise inequality
print("\nElement-wise inequality:")
print(df_1.ne(3))

# Element-wise less than
print("\nElement-wise less than:")
print(df_1.lt(3))

# Element-wise less than or equal to
print("\nElement-wise less than or equal to:")
print(df_1.le(3))

# Element-wise greater than
print("\nElement-wise greater than:")
print(df_1.gt(3))

# Element-wise greater than or equal to
print("\nElement-wise greater than or equal to:")
print(df_1.ge(3))

Element-wise equality:
       A      B
0  False  False
1  False  False
2   True   True
3  False  False
4  False  False

Element-wise inequality:
       A      B
0   True   True
1   True   True
2  False  False
3   True   True
4   True   True

Element-wise less than:
       A      B
0   True  False
1   True  False
2  False  False
3  False   True
4  False   True

Element-wise less than or equal to:
       A      B
0   True  False
1   True  False
2   True   True
3  False   True
4  False   True

Element-wise greater than:
       A      B
0  False   True
1  False   True
2  False  False
3   True  False
4   True  False

Element-wise greater than or equal to:
       A      B
0  False   True
1  False   True
2   True   True
3   True  False
4   True  False

In [38]:
# Selects rows with a conditional
df[df['Rating'] == 10]

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0

In [39]:
# Select rows with multiple conditional
df[(df['Rating'] > 8) & df['Released'] < 1990]

,Artist,Album,Released,Length,Genre,Music Recording Sales (millions),Claimed Sales (millions),Released.1,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

<h2 id="cleaning">5. Data Cleaning and Preprocessing</h2>

In [40]:
# Rename columns with dictionaries
new_columns = {'Music Recording Sales (millions)': 'Recroding Sales (M)',
               'Claimed Sales (millions)': 'Claimed Sales (M)',
               'Released.1' : 'Date Released',
               'Released': 'Year Released'               
               }
df.rename(columns=new_columns, inplace=True)
df

,Artist,Album,Year Released,Length,Genre,Recroding Sales (M),Claimed Sales (M),Date Released,Soundtrack,Rating
0,Michael Jackson,Thriller,1982,0:42:19,"pop, rock, R&B",46.0,65,30-Nov-82,NaN,10.0
1,AC/DC,Back in Black,1980,0:42:11,hard rock,26.1,50,25-Jul-80,NaN,9.5
2,Pink Floyd,The Dark Side of the Moon,1973,0:42:49,progressive rock,24.2,45,01-Mar-73,NaN,9.0
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,17-Nov-92,Y,8.5
4,Meat Loaf,Bat Out of Hell,1977,0:46:33,"hard rock, progressive rock",20.6,43,21-Oct-77,NaN,8.0
5,Eagles,Their Greatest Hits (1971-1975),1976,0:43:08,"rock, soft rock, folk rock",32.2,42,17-Feb-76,NaN,7.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,15-Nov-77,Y,7.0
7,Fleetwood Mac,Rumours,1977,0:40:01,soft rock,27.9,40,04-Feb-77,NaN,6.5

In [41]:
# Convert 'Released' columns to datetime data type
df['Date Released'] = pd.to_datetime(df['Date Released'], format='%d-%b-%y')
df.dtypes

Artist                         object
Album                          object
Year Released                   int64
Length                         object
Genre                          object
Recroding Sales (M)           float64
Claimed Sales (M)               int64
Date Released          datetime64[ns]
Soundtrack                     object
Rating                        float64
dtype: object

In [42]:
# Remove missing values
df.dropna(inplace=True)
df

,Artist,Album,Year Released,Length,Genre,Recroding Sales (M),Claimed Sales (M),Date Released,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,1992,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
6,Bee Gees,Saturday Night Fever,1977,1:15:54,disco,20.6,40,1977-11-15,Y,7.0

The ```.dropna()``` remove all the rows with nan values.
If you want to remove missing values considering some colums us ```.dropna(subset=['column1', 'column2', ...])```

In [43]:
# Remove a column
df.drop(columns=['Year Released'], inplace=True)
df

,Artist,Album,Length,Genre,Recroding Sales (M),Claimed Sales (M),Date Released,Soundtrack,Rating
3,Whitney Houston,The Bodyguard,0:57:44,"R&B, soul, pop",27.4,44,1992-11-17,Y,8.5
6,Bee Gees,Saturday Night Fever,1:15:54,disco,20.6,40,1977-11-15,Y,7.0

<h2>Read/Save Other Data Formats</h2>

| Data Formate  | Read           | Save             |
| ------------- |:--------------:| ----------------:|
| csv           | `pd.read_csv()`  |`df.to_csv()`     |
| json          | `pd.read_json()` |`df.to_json()`    |
| excel         | `pd.read_excel()`|`df.to_excel()`   |
| hdf           | `pd.read_hdf()`  |`df.to_hdf()`     |
| sql           | `pd.read_sql()`  |`df.to_sql()`     |
| ...           |   ...          |       ...        |